# Generated by Django 3.0.6 on 2020-06-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=16)),
                ('adminPwd', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=16)),
                ('userPwd', models.CharField(max_length=16)),
            ],
        ),
    ]
