# Generated by Django 3.0.6 on 2020-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=16)),
                ('Date_of_Joining', models.DateField()),
                ('Date_of_Birth', models.DateField()),
                ('Salary', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=50)),
            ],
        ),
    ]
