# Generated by Django 3.0.6 on 2020-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountants',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=16)),
                ('userPwd', models.CharField(max_length=16)),
                ('dateOfJoining', models.DateField()),
                ('dateOfBirth', models.DateField()),
                ('salary', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Administrators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminName', models.CharField(max_length=16)),
                ('adminPwd', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branches',
        ),
        migrations.DeleteModel(
            name='Accountant',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='Branch',
            new_name='branch',
        ),
    ]
