# Generated by Django 3.0.6 on 2020-06-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=16)),
                ('userPwd', models.CharField(max_length=16)),
                ('dateOfJoining', models.DateField()),
                ('dateOfBirth', models.DateField()),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralUsers',
        ),
    ]
