# Generated by Django 3.0.6 on 2020-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0002_auto_20200726_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountants',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
