# Generated by Django 3.0.6 on 2020-07-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0003_auto_20200726_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountants',
            name='branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accountants',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
