# Generated by Django 3.0.6 on 2020-07-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0003_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountants',
            name='branch',
            field=models.CharField(default='India/South Asia', max_length=50),
            preserve_default=False,
        ),
    ]
