# Generated by Django 3.0.6 on 2020-07-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0004_accountants_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountants',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
