# Generated by Django 3.0.6 on 2020-07-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0004_auto_20200727_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=16)),
                ('Password', models.CharField(max_length=16)),
                ('Date_of_Joining', models.DateField()),
                ('DOB', models.DateField()),
                ('Salary', models.CharField(max_length=10)),
                ('Branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Administrators',
            new_name='Administrator',
        ),
        migrations.RenameModel(
            old_name='Branches',
            new_name='Branch_Name',
        ),
        migrations.DeleteModel(
            name='Accountants',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='adminPwd',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='adminName',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='branch_name',
            old_name='branch',
            new_name='Branch',
        ),
    ]
