# Generated by Django 3.0.6 on 2020-07-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0005_auto_20200727_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
