# Generated by Django 3.0.6 on 2020-07-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0006_delete_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountant',
            name='Password',
        ),
    ]
