# Generated by Django 3.0.6 on 2020-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bPay', '0007_remove_accountant_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=50)),
                ('Mobile', models.BigIntegerField()),
                ('Father_name', models.CharField(max_length=50)),
                ('Mother_name', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Date_of_Joining', models.DateField()),
                ('Date_of_Submission', models.DateField()),
                ('Paid', models.IntegerField()),
                ('Fee', models.IntegerField()),
                ('Balance', models.IntegerField()),
                ('Address', models.TextField()),
                ('Description', models.TextField()),
                ('Trainer', models.CharField(max_length=50)),
            ],
        ),
    ]
