from django.conf.urls import url
from bPay import views

urlpatterns = [
    url(r'^$', views.loginPageView),
    url(r'^adminLogin/$', views.adminLoginPageView),
    url(r'^accountantCreation/$', views.accountantCreationPageView),
    url(r'^adminAuth', views.adminAuth, name='authAdmin'),
    url(r'^accountantAuth', views.accountantAuth, name='authAccountant'),
    url(r'^adminHome', views.route2adminHome, name='adminHome'),
    url(r'^accountantHome', views.route2accountantHome, name='accountantHome'),
    url(r'^createAccountant', views.createAccountant, name='createAccountant'),
    url(r'^accountantsDetails', views.adminGetDetails, name='getDetailsAd1'),
    url(r'^accountantAllDetails', views.adminGetAllDetails, name='getDetailsAd2'),
    url(r'^studentsDetails', views.accountantGetDetails, name='getDetailsAc1'),
    url(r'^studentFeeDetails', views.accountantGetFeeDetails, name='getDetailsAc2'),
    url(r'^studentCourseDetails', views.accountantGetCourseDetails, name='getDetailsAc3'),
    url(r'^studentGeneralDetails', views.accountantGetGeneralDetails, name='getDetailsAc4'),
    #url(r'^allDetails/(?P<acnt_pk>\w+)/(?P<acnts>(.*))', views.adminGetDetails2, name='getDetailsA2'),
    url(r'^logOut', views.logOut, name='logOut'),
    url(r'^deleteData', views.deleteData, name='deleteData'),
    url(r'^acHome', views.acHome, name='acHome'),
    url(r'^adHome', views.adHome, name='adHome'),
    url(r'^acRegisterStudent/$', views.accessRegisterStudentPage),
    url(r'^acModifyStudent/$', views.accessModifyStudentPage),
    url(r'^registerStudent/$', views.registerStudentPage),
    url(r'^modifyStudent/$', views.modifyStudentPage),
    url(r'^contact/$', views.contactPage),
    url(r'^registerStudentDetails', views.registerStudentDetails, name='registerStudentDetails'),
    url(r'^getStudentDetails', views.getStudentDetails, name='getStudentDetails'),
    url(r'^fillStudentDetails', views.fillStudentDetails, name='fillStudentDetails'),
    #url(r'^fillStudentDetails/(?P<acnt_pk>\w+)/$', views.fillStudentDetails, name='fillStudentDetails'),
    url(r'^modifyStudentDetails', views.modifyStudentDetails, name='modifyStudentDetails'),   
    url(r'^sendMail', views.sendMail, name='sendMail'),   
]